addSbtPlugin("com.47deg"  % "sbt-microsites" % "0.9.0")
addSbtPlugin("com.eed3si9n" % "sbt-unidoc" % "0.4.2")
addSbtPlugin("org.scalastyle" %% "scalastyle-sbt-plugin" % "1.0.0")
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.5.1")
addSbtPlugin("org.xerial.sbt" % "sbt-sonatype" % "2.0") 
addSbtPlugin("com.jsuereth" % "sbt-pgp" % "1.1.1")
addSbtPlugin("pl.project13.scala" % "sbt-jmh" % "0.3.6")
addSbtPlugin("com.github.gseitz" % "sbt-release" % "1.0.11")
